Fix #155: Consistent handling of URIs
eclipse-emfcloud/emfcloud-modelserver pull request #176
Opened 2022-02-26 14:40 UTC by cdamus

_**Note** that this PR is based on #169 and probably should not be merged before that one is ready to merge. The only new change in this context is commit 8ffc4ed78f48d6975f33fd1712842a8b281fca3c._

## For the V2 API

This PR introduces two new core services for the management of URIs: a `ModelURIConverter` and a `ResourceSetFactory`.

### ResourceSetFactory

The resource set factory service creates the resource set identified by a `modeluri` query parameter for management of that resource and its associated companion resources. The `DefaultModelResourceManager` delegates to this service to create its resource sets.

The main thing that this factory does is to configure the resource set it creates with the `ModelURIConverter` service as the resource set's URI converter. This ensures that loading of resources within the resource set, whether directly by request handlers or indirectly via proxy resolution, uses the same rules for normalizing URIs and, especially, resolving relative URIs against the workspace location.

Model servers that wish to customize the resource sets that they create can now bind a subclass of the `DefaultResourceSetFactory` instead of a custom model resource manager. The custom factory should extend the superclass behaviour with registration of resource factories or whatever else the particular server needs.

### ModelURIResolver

This service extends the EMF `URIResolver` interface with APIs for getting the target model URI (usually the `modeluri` query parameter) out of the request or socket context as an EMF `URI` that is resolved against workspace root location in the case of an incoming relative URI. The `DefaultModelURIResolver` class attempts to be quite flexible in parsing incoming model URIs that look like file paths, especially Windows paths and naïve URIs based on them, such as

- relative\to\workspace\model.xmi
- relative/to/workspace/model.xmi
- c:\path\to\workspace\model.xmi
- /c:/path/to/workspace/model.xmi
- file:/c:/path/to/workspace/model.xmi
- file:/c:\path\to\workspace\model.xmi

> _Hopefully this will provide the benefit of resolving some outstanding bugs on Windows platform. In testing on Windows, I was able to throw pretty much any kind of URI or file path at the server in the `modeluri` query parameter._

The `ModelURIResolver` also provides API for relativizing outgoing model URIs against the workspace root, for example for responses to the `GET` request on the `modeluris` endpoint. All endpoint handlers that work with model URIs either as inputs or as outputs should use this new service to resolve incoming URIs and deresolve outgoing URIs for consistency.

The `DefaultModelURIResolver` is configurable for different resolution and deresolution rules for different API versions. This is managed by injection of

- `Function<URI, Optional<URI>>` mapped to an `APIVersionRange` for resolution of URIs. The optional result allows URIs to be rejected. For example, the default binding for API v2 and above allows only relative URIs in the query parameter, which then are resolved against the workspace location
- `Function<URI, URI>` mapped to an `APIVersionRange` for deresolution of URIs, generating URIs relative to the workspace location for response to the client

These version-specific dependencies are managed by new classes `APIVersion`, `APIVersionRange`, and `APIVersionMap` which last allows to map objects by API version range to look up the entry most applicable to a given API version. The intent is that these can help with future API-specific functionality and API evolution to new versions.

New `configureModelURIResolvers(...)` and `configureModelURIDeresolvers(...)` hooks in the `DefaultModelServerModule` make it easy for subclasses to replace or add URI resolver and deresolver bindings for whatever API version ranges they need to customize.

The default injections of URI handling in the `DefaultModelURIResolver` for API v2:

- accept only relative URIs in the `modeluri` query parameter, which then are resolved against the workspace root. This can be overridden by clients by injecting a custom `Predicate<? super URI>` named `modelURIValidator`
- deresolve all outgoing absolute URIs against the workspace root to get relative URIs

## For the V1 API

The default injections of URI handling in the `DefaultModelURIResolver` for API v1:

- accept both absolute and relative URIs in the `modeluri` query parameter. Relative URIs, of course, are resolved against the workspace location
- leave outgoing absolute URIs as they are

For compatibility with existing server implementations, the v1 URI resolver delegates to the `adaptModelUri(String)` method of the `DefaultModelResourceManager` class. This method is now deprecated and is not used in API v2.

Essentially, deresolution is a no-op for API v1 as most endpoints in v1 return absolute URIs for everything. The exception is the `modeluris` endpoint, which is updated with a special case for v1 to explicitly deresolve the model URIs that it returns.

A goal of this refactoring is to leave the API v1 behaviour exactly as it was while making the handling of URIs in API v2 and beyond more consistent and by default enforcing wherever possible that URIs be relative to the workspace location so that clients need even be aware of what the workspace URI is.

## Other Tidbits

The new injections in existing services try to be API compatible as much as is practical, so that servers extending this framework will continue to function normally without changes. This is only really assured for cases where the services are obtained from the Guice injector which, in normal operation, is already assumed. Unit tests, however, that often do directly construct and configure these services will need be adapted to these changes because there are new required dependencies.

Another detail to note is that the `DefaultModelResourceManager` presented a particular challenge for compatibility. In particular, it has an `initialize()` method that subclasses were expected to override to perform initialization of the workspace, but this was called from the constructor.
Not only is that an anti-pattern that leads to invocation of methods on objects that have not yet run their subclass constructors, but it runs the initialization before field or method injection can occur. To solve this issue, this PR introduces an `@Initialize` annotation for a method that the Guice injector will call only after all dependencies are injected. This is analogous to `@PostConstruct` in Eclipse e4 or `@postContruct()` in inversify.js. The implementation of this is provided by a new `AbstractModuleWithInitializers` class that can be used to configure bindings that use this new `@Initialize` mechanism. Again a consequence for unit tests that do not use Guice to configure services is that initializer methods would need to be invoked explicitly.

Contributed on behalf of STMicroelectronics.

2022-03-10 13:01 UTC, cdamus commented
Commit 10a7909b3a923781887e416752ff48a1d2542342 rebases the PR onto the latest `master` branch to resolve conflicts.

2022-03-11 12:19 UTC, ndoschek requested changes
Thanks a lot for this PR @cdamus!
Changes looks great to me and I especially appreciate the detailed description and JavaDocs! :tada: 

I only have two minor comments - one inline and the following:
The `org.eclipse.emfcloud.modelserver.emf.util` package is not exported (therefore the `JsonPatchHelper` cannot be imported if extending a `*ModelResourceManager`).
I already integrated your changes locally with a project of ours and added a custom `ResourceSetFactory`. Except for the mentioned limitation it looks great to me and was really intuitive to implement.

2022-03-11 13:23 UTC, cdamus commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelController.java
> +         // resolveWorkspaceURIs(cCommand);
🤦

2022-03-11 13:38 UTC, cdamus commented
Thanks @ndoschek for the review! 🌟  I'm sure it was a bit of a twisted slog to get through.

I don't know how that package export went AWOL (it must have been exported previously, otherwise another PR wouldn't have worked) but there were also other packages that weren't exported so I fixed those, too.

2022-03-11 15:53 UTC, ndoschek approved these changes
Thanks for the quick update! LGTM :+1:

2022-03-11 15:53 UTC, merged