Align Java client API with protocol and typescript client
eclipse-emfcloud/emfcloud-modelserver pull request #53
Opened 2020-11-26 16:14 UTC by martin-fleck-at

- Add missing method for listing model uris: getModelUris
- Ensure getAll returns a list of models and supports custom format
- Introduce dedicated model class with modelUri and content properties
- Add client test cases for new and changed methods
- Fix setup of modelserver.lib

Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>

2020-11-30 10:23 UTC, ndoschek requested changes
Thank you Martin for this change! :+1: Code looks good to me, I only noticed one minor API return type mismatch, would be great if you could have a look at it, thanks!

2020-11-30 10:23 UTC, ndoschek commented on bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClientApiV1.java
> +   CompletableFuture<Response<List<Model<EObject>>>> getAll(String format);
We should keep the generic return type `<A>` in this case, as the current `ModelServerClient` implements the `ModelServerClientApi<EObject>` anyway.

2020-11-30 10:23 UTC, ndoschek commented on README.md
> +   CompletableFuture<Response<List<Model<EObject>>>> getAll(String format);
Keep generic type `<A>` here as well.

2020-12-01 10:34 UTC, martin-fleck-at commented
@ndoschek Thank you for your review, Nina! You are absolutely right, I pushed a follow-up commit that should fix it.

2020-12-01 10:45 UTC, ndoschek approved these changes

2020-12-01 10:51 UTC, merged