Fix broadcasting of Undo/Redo updates especially for XMI listeners
eclipse-emfcloud/emfcloud-modelserver pull request #59
Opened 2021-01-12 10:45 UTC by ndoschek

- Ensure undo/redo commands can be encoded to broadcast to all listeners
  - Especially for XMI listeners it is therefore necessary to encode the commands before actual undo/redo as the encoding using the already changed resource leads cannot be completed.

Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>

2021-01-15 10:04 UTC, martin-fleck-at requested changes
Hello Nina, thank you very much for that fix/change. As far as I can tell everything works as expected now, great work! I have a few minor comments that may be considered but other than that I think we can merge it :-)

2021-01-15 10:04 UTC, martin-fleck-at commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelController.java
> +         Map<String, JsonNode> encodings = sessionController.getCommandEncodings(modeluri, undoCommand);
Please add some comment as to why we do the encoding in all formats here. As far as I remember the reasoning was something like this: In order to encode certain commands (e.g., commands that delete something) we need all element information, e.g., the info which element was deleted before it is gone. Therefore we encode the command in all formats and provide them to the model repository which will select the correct format for each subscribed client. This means that we encode the command once for all formats. The alternative would be to encode it once per subscribed client.

2021-01-18 14:09 UTC, ndoschek commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
> +            return EcoreUtil.copy(commandCodec.encode(undoCommand));
Yes, you are right, thanks for spotting that! It is a leftover from error investigation, I removed it and also for redo pendant.

2021-01-18 16:48 UTC, martin-fleck-at approved these changes
Thank you for the update, everything works great now!

2021-01-18 16:48 UTC, merged