#12, #78: [WIP] Extend command API
eclipse-emfcloud/emfcloud-modelserver pull request #84
Opened 2021-02-22 21:00 UTC by martin-fleck-at

- Make client commands more extensible
-- Use String for type argument instead of enum
-- Add generic properties to provide custom information

- Make command codec injectable with client contributions
-- Clients can contribute translation for their commands based on type
-- Move previous implementation to custom EMF command contributions
-- Move shared code into dedicated utility class
-- Provide EMFCommandCodec for easier non-DI usability

- Use transactional editing domain and command stack
-- Perform model update on command stack (is now undoable)
-- Add EMF Transaction to target platform and maven build

- Extend Command model with CommandExecutionResult
-- Provide original command and affected EObject in result

- Remove 'edit' command with EMF commands from Java Client API

- Add custom command to Coffee example
-- Command simply adds the given text to all tasks

TODO:
- Fix test cases
- Fix dangling reference issue when performing undo/redo
- Add custom command showcase to Theia client

Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>

2021-02-23 11:01 UTC, ndoschek requested changes
Thank you very much for this excellent contribution Martin!
Overall the functionality seems to work great, and I am a huge fan of the re-worked "command concept"! :+1: 
I am currently still in the process of testing, but meanwhile I found some superficial issues, which might be fixed rather quickly I assume.

2021-02-23 11:42 UTC, martin-fleck-at commented on bundles/org.eclipse.emfcloud.modelserver.edit/src/org/eclipse/emfcloud/modelserver/edit/EMFCommandCodec.java
> +   }
We don't use it anymore, no. I just kept it for people who might still want to use it. But maybe it is better to remove it, you are right.

2021-02-23 11:42 UTC, martin-fleck-at commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelController.java
> +         sessionController.commandExecuted(modeluri, encodings);
Oh yeah, sure, good idea!

2021-02-23 14:39 UTC, martin-fleck-at commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelRepository.java
> +   Optional<CCommandExecutionResult> redo(String modeluri);
I cleaned those methods up, thank you!

2021-02-23 14:43 UTC, martin-fleck-at commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerEditingDomain.java
> +         return commandStack.getUndoCommand();
I modified the code ab it and cleaned it up, thank you!

2021-02-23 14:48 UTC, martin-fleck-at commented
@ndoschek Thank you very much for your review, I took another look at the things you mentioned and pushed a new follow-up commit that fixes several things. I also fixed the test cases, at least for me locally they run through :-)

2021-02-26 09:18 UTC, ndoschek requested changes
Thank you again for updating the PR and especially for fixing the tests! :+1: 
So far, the functionality looks great to me and it is quite intuitive to adapt to the new concept!
But I noticed a few minor things:
- The `XmiToEObjectSubsubscriptionListener` needs to be updated as well as it still excpects a `CCommand` instead of the new result type.
- Please update the README
- It would be great if we provided a custom command example in Java somewhere, either in the README and/or in the `ExampleModelServerSubscriptionClient` - what do you think?

2021-03-01 15:38 UTC, martin-fleck-at commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionController.java
> +   public void commandExecuted(final String modeluri, final CCommandExecutionResult exeuction) {
Done

2021-03-01 15:39 UTC, martin-fleck-at commented on bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionController.java
> +      broadcastIncrementalUpdates(modeluri, exeuction);
Done

2021-03-01 15:40 UTC, martin-fleck-at commented
@ndoschek I pushed an update with all the requested changes. I also moved the code a little bit around and renamed CommandCodecContribution to CommandContribution to avoid any codec confusion ;-)

2021-03-02 08:46 UTC, ndoschek approved these changes
Thank you very much Martin for updating the PR, everything works now as expected! :+1: 
My previous confusion about the AddCommand is resolved as well - I tested it again with pure EMF commands and it works great as well!
Thank you again for this great improvement!

2021-03-02 08:55 UTC, merged